services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app/api
      # Esse comando blinda o node_modules do container para não ser esmagado pelo Windows
      - /usr/src/app/api/node_modules 

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      # Corrigido: Mapeando a 3001 do PC para a 3001 do container (onde o Next tá rodando)
      - "3001:3001" 
    env_file:
      - ./web/.env.local
    volumes:
      - ./web:/usr/src/app/web
      # Blinda o node_modules do frontend também
      - /usr/src/app/web/node_modules 
    depends_on:
      - api